### ISSUE TITLE
Bug: GardenActivityTest need fix, it doesn't work well

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-sunflower#60]
Hi try to test from command line 

`./gradlew connectedAndroidTest`

```
com.google.samples.apps.sunflower.GardenActivityTest > clickOnPlantListDrawerMenuItem_StartsPlantListActivity[SM-G950F - 7.0] FAILED 
        android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
        at dalvik.system.VMStack.getThreadStackTrace(Native Method)
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: -2
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: numtests=14
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: stream=
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: test=clickOnAndroidHomeIcon_OpensAndClosesNavigation
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: class=com.google.samples.apps.sunflower.GardenActivityTest
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: current=2
11:24:24 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: 1


com.google.samples.apps.sunflower.GardenActivityTest > pressDeviceBack_CloseDrawer_Then_PressBack_Close_App[SM-G950F - 7.0] FAILED 
        android.support.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
        at dalvik.system.VMStack.getThreadStackTrace(Native Method)
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: -2
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: numtests=14
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: stream=
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: test=onRotate_NavigationStaysOpen
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: class=com.google.samples.apps.sunflower.GardenActivityTest
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: current=4
11:25:30 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: 1


```

**Comment by XinyueZ** [comment]
Problem happened while my test devices are all in "sleep".
